##Circleci version name

version: 2.1

## Jobs

jobs:
  
  deploy to s3: 
    docker:
      - image: amazon/aws-cli:2.7.17
        command: ""
    steps:
      - checkout
       # You can get this ID in the section where you registered the SSH K
      - run:
          name: Deploying files in s3 bucket
          command: |
            aws --version
            aws s3 sync . s3://${BUCKET_NAME} --delete
      
      
             
workflows:
  # Name the workflow "welcome"
  Deploying to s3 bucket:
    # Run the welcome/run job in its own container
    jobs:
      #- create_infrastructure 
      - deploy to s3